---
variant: flatcar
version: 1.0.0
systemd:
  units:
    - name: locksmithd.service
      mask: true
    - name: update-engine.service
      enabled: true
    - name: iscsid.service
      enabled: true
    - name: iscsid-initiatorname.service
      dropins:
        - name: iscsi-initiatorname.conf
          contents: |
            [Install]
            WantedBy=multi-user.target
      enabled: true
    - name: install-opt-dir.service
      enabled: true
      contents: |
        [Unit]
        Description=Install /opt directories
        ConditionPathIsDirectory=!/opt/libexec
        ConditionPathIsDirectory=!/opt/libexec.wd
        
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/mkdir -p /opt/libexec /opt/libexec.wd
        
        [Install]
        WantedBy=multi-user.target
    - name: usr-libexec.mount
      enabled: true
      contents: |
        [Unit]
        Description=Allow k8s CNI plugins to be installed
        Before=local-fs.target
        Requires=install-opt-dir.service
        ConditionPathExists=/opt/libexec
        ConditionPathExists=/opt/libexec.wd
        
        [Mount]
        Type=overlay
        What=overlay
        Where=/usr/libexec
        Options=lowerdir=/usr/libexec,upperdir=/opt/libexec,workdir=/opt/libexec.wd
        
        [Install]
        WantedBy=local-fs.target

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDObbEnWiD2nQRu9REtf7T3W0hlTB0DeOpej2nL3YUTfLGn+9I/UAZmBUFhArl+wjLHf9efogQV7GH24beTYN4IhVMVOWYsyybxi50CMzR4tZNJfmH2wOIdJxGhgUyKy/BprLJfJ2JNnRoUxOXqNHu5o1hSUzFHGJ/dIM5a5Gu0sAfUh1Usd0pd6eC9m6OqvKgXRq5TLyBgdID5qIK0zhxaduOJ66afw9kEGqn0pm94KfYS27iZ1FtWU1ppjy6Sf6mSOsAHFQ3on0MiebqvDi4J9MVQ6nuqxbJsFKoVlqvwGbMwpyjDjeoW3uNC+EuE3ebD9R4i51Reoeobsu9JsRE8+S4ruJK5jGGO/HIrPfFavtdvNBT6gWH0FcRa0oKynSFHTUcIM53djK67IxPCWTcR3xwvdDHvyIBp1Fa/jfbTgUGLeds3RyX5Sdv64nqPILmZ1kLb5E9DCg5hl1XDb9LrJPergeAnOYUzbFsTODjGOrwzsLMxx+E2VTQ1A997lbE= blablu@blablus-MacBook-Pro.local
        - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAhwNFQEz1l54YexhQhU5/7fVNcwVmowA9l2HbtZL75299UCo5efY4YXUBBERSW8SR/EauO5BeZdb9Bddp7+DyZ/xaLy8H9xW7OuD4qIxasAX0YE4c+LnDDohwCszMjiZKLD/vH/k8hYEdOf/HhLZ3o9JUzj4ENMIwI/34GNHsb3dLoBuzFRES4AjUIY8DPlSjr4QwgM2RZHHCkLt51PLs6F5e8PpR8XvwHO7ybdKY7vEDJoQKM0p4ddL1pwQZisf2c8h1R0CUt248QDwsexSyZBo5vQ2KHuGS14Q+ul7G90gDKXUaBOZMlMAQPVH3SLmrjvD6Y7S0IvAJWPFxEW/LHw== rsa-key-olb-desktop
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAP83JsqhLdMKyH8HRTG10FK5rPeczmtPcjB+qnt5bo6 seb_buttah
storage:
  files:
    - path: /etc/modules-load.d/iscsi_tcp.conf
      mode: 0420
      contents:
        inline: |
          iscsi_tcp
    - path: /etc/sysctl.d/buttah.conf
      mode: 0644
      contents:
        inline: |
          fs.inotify.max_user_instances=1280
          fs.inotify.max_user_watches=655360
kernel_arguments:
  should_exist:
    - intel_iommu=on