variant: flatcar 
version: 1.0.0
systemd:
  units:
    - name: flatcar-install.service
      enabled: true
      contents: |
        [Unit]
        Description=Flatcar Container Linux Installation

        [Service]
        Type=oneshot
        ExecStart=/root/flatcar-install.sh

        [Install]
        WantedBy=multi-user.target
storage:
  links:
    - filesystem: "root"
      path: "/etc/systemd/system/multi-user.target.wants/flatcar-install.service"
      target: "/etc/systemd/system/flatcar-install.service"
  files:
    - path: /root/flatcar-install.sh
      mode: 700
      contents:
        source: "data:;base64,IyEvYmluL3NoCgovdXNyL2Jpbi9jdXJsIC1MIGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9idXR0YWh0b2FzdC9pZ25pdGlvbi9tYWluL3Byb2R1Y3Rpb24uanNvbiAtbyBpZ25pdGlvbi5qc29uCi91c3IvYmluL2ZsYXRjYXItaW5zdGFsbCAtcyAtQyBzdGFibGUgLWkgLi9pZ25pdGlvbi5qc29uCi91c3Ivc2Jpbi9yZWJvb3QK"
